# Generated by Django 4.2.3 on 2023-08-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('composition', models.TextField(default='')),
                ('prodapp', models.TextField(default='')),
                ('category', models.CharField(choices=[('CH', 'casual half hand shirt'), ('CFRT', 'casual full sleeve round neck Tshirt'), ('CHRT', 'casual half sleeve round neck Tshirt'), ('CF', 'casual full hand shirt'), ('JN', 'jeans'), ('CHCT', 'casual half sleeve coller Tshirt')], max_length=4)),
                ('product_image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
