# Generated by Django 4.2.3 on 2023-08-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CF', 'casual full hand shirt'), ('JN', 'jeans'), ('CFRT', 'casual full sleeve round neck Tshirt'), ('CHCT', 'casual half sleeve coller Tshirt'), ('CHRT', 'casual half sleeve round neck Tshirt'), ('CH', 'casual half hand shirt')], max_length=4),
        ),
    ]
