# Generated by Django 4.2.3 on 2023-08-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CH', 'casual half hand shirt'), ('CHRT', 'casual half sleeve round neck Tshirt'), ('CF', 'casual full hand shirt'), ('CHCT', 'casual half sleeve coller Tshirt'), ('CFRT', 'casual full sleeve round neck Tshirt'), ('JN', 'jeans')], max_length=4),
        ),
    ]
