# Generated by Django 4.2.3 on 2023-08-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CFRT', 'casual full sleeve round neck Tshirt'), ('CHRT', 'casual half sleeve round neck Tshirt'), ('CF', 'casual full hand shirt'), ('CH', 'casual half hand shirt'), ('CHCT', 'casual half sleeve coller Tshirt'), ('JN', 'jeans')], max_length=4),
        ),
    ]
