# Generated by Django 4.2.3 on 2023-08-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CFRT', 'casual full sleeve round neck Tshirt'), ('CHCT', 'casual half sleeve coller Tshirt'), ('CH', 'casual half hand shirt'), ('CHRT', 'casual half sleeve round neck Tshirt'), ('JN', 'jeans'), ('CF', 'casual full hand shirt')], max_length=4),
        ),
    ]
