# Generated by Django 4.2.3 on 2023-08-23 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='product',
            name='prodapp',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CFRT', 'casual-full-sleeve-round-neck-Tshirts'), ('CHRT', 'casual-half-sleeve-round-neck-Tshirts'), ('CHCT', 'casual-half-sleeve-collar-Tshirts'), ('CFS', 'casual-full-size-shirts'), ('CHS', 'casual-half-size=shirts'), ('JN', 'jeans')], max_length=4),
        ),
    ]
