# Generated by Django 4.2.3 on 2023-08-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_product_composition_remove_product_prodapp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('selling_price', models.FloatField()),
                ('discounted_price', models.FloatField()),
                ('description', models.TextField()),
                ('category', models.TextField(choices=[('JN', 'jeans'), ('CHRT', 'casual-half-sleeve-round-neck-Tshirts'), ('CFRT', 'casual-full-sleeve-round-neck-Tshirts'), ('CHCT', 'casual-half-sleeve-collar-Tshirts'), ('CHS', 'casual-half-size=shirts'), ('CFS', 'casual-full-size-shirts')], max_length=4)),
            ],
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
