# Generated by Django 4.2.3 on 2023-08-25 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_dress_delete_cloth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='category',
            field=models.CharField(choices=[('CHCT', 'casual-half-sleeve-collar-Tshirts'), ('JN', 'jeans'), ('CHS', 'casual-half-size-shirts'), ('CHRT', 'casual-half-sleeve-round-neck-Tshirts'), ('CFS', 'casual-full-size-shirts'), ('CFRT', 'casual-full-sleeve-round-neck-Tshirts')], max_length=4),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('zipcode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
