# Generated by Django 4.2.3 on 2023-08-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_dress_category_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='category',
            field=models.CharField(choices=[('CFS', 'casual-full-size-shirts'), ('CHCT', 'casual-half-sleeve-collar-Tshirts'), ('CHRT', 'casual-half-sleeve-round-neck-Tshirts'), ('JN', 'jeans'), ('CFRT', 'casual-full-sleeve-round-neck-Tshirts'), ('CHS', 'casual-half-size-shirts')], max_length=4),
        ),
    ]
