# Generated by Django 4.2.3 on 2023-08-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_dress_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='category',
            field=models.CharField(choices=[('CHS', 'casual-half-size-shirts'), ('CFS', 'casual-full-size-shirts'), ('CFRT', 'casual-full-sleeve-round-neck-Tshirts'), ('CHCT', 'casual-half-sleeve-collar-Tshirts'), ('JN', 'jeans'), ('CHRT', 'casual-half-sleeve-round-neck-Tshirts')], max_length=4),
        ),
    ]
