# Generated by Django 4.2.3 on 2023-08-26 04:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0013_alter_dress_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='category',
            field=models.CharField(choices=[('JN', 'jeans'), ('CFS', 'casual-full-size-shirts'), ('CHCT', 'casual-half-sleeve-collar-Tshirts'), ('CHRT', 'casual-half-sleeve-round-neck-Tshirts'), ('CHS', 'casual-half-size-shirts'), ('CFRT', 'casual-full-sleeve-round-neck-Tshirts')], max_length=4),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.dress')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
